name: Swift CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd Example
          pod install --repo-update
      - name: Build Example Project
        run: |
          cd Example
          xcodebuild -workspace ImageKit.xcworkspace -scheme imagekit-Example -destination 'platform=iOS Simulator,name=iPhone 11' clean build
          
  lint-pod:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Cocoa Pod
        run: pod lib lint

  test-example:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd Example
          pod install --repo-update
      - name: Test Example Project
        run: |
          cd Example
          xcodebuild -workspace ImageKit.xcworkspace -scheme imagekit-Example -destination 'platform=iOS Simulator,name=iPhone 11' clean test
